version: "3.9"
services:
  db:
    image: mysql:8.4
    container_name: mysql-container3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123@
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    networks:
      - spring-net
  spring-api:
    image: su54_pos_api
    restart: always
    container_name: su54_pos_api
    ports:
      - "8090:8080"
    depends_on:
      - db
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    networks:
      - spring-net
networks:
  spring-net:

