version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: keycloak-postgres-su54
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak:
      image: quay.io/keycloak/keycloak:25.0.1
      container_name: keycloak-server-su54
      restart: always
      depends_on:
        - postgres
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak123

        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin123

        KC_HOSTNAME: https://sumchanthou.com
        KC_PROXY: edge
        KC_HTTP_ENABLED: true
      command: start
      ports:
        - "8081:8080"
  db:
    image: mysql:8.4
    container_name: mysql-container-su54
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123@
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    networks:
      - spring-net
  spring-api:
    image: su54_pos_api
    restart: always
    container_name: su54-pos-api
    ports:
      - "8090:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads/
    networks:
      - spring-net
networks:
  spring-net:
volumes:
  uploads:
  postgres_data:


